### ISSUE TITLE
Super enter ls issue 

### ISSUE THREAD

**Issue by afk-mario** [subnixr/minimal#1]
When I use Super Enter I get this:

```
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
```

**Comment by subnixr** [comment]
That feature relies on `ls` from GNU `coreutils` package (which is default on most if not all Linux distros). Try install it for your system (OSX I guess) and let me know

**Comment by afk-mario** [comment]
That was it, Thanks!
