### ISSUE TITLE
Antigen install not working

### ISSUE THREAD

**Issue by rkayaith** [subnixr/minimal#14]
Running `antigen theme subnixr/minimal` gives this error:
```
-antigen-load:source:19: no such file or directory: /home/abc/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-subnixr-SLASH-minimal.git//.zsh-theme
```

I think the correct command is `antigen theme subnixr/minimal minimal`, which still gives this error since it's looking for a `.zsh-theme` file:
```
-antigen-load:source:19: no such file or directory: /home/abc/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-subnixr-SLASH-minimal.git/minimal.zsh-theme
```

Renaming `minimal.zsh -> minimal.zsh-theme` fixes that. You could also make a theme file that sources the current one:
``` bash
# minimal.zsh-theme
source ${0%/*}/minimal.zsh
```

**Comment by subnixr** [comment]
Thanks for reporting the issue.

The problem is that I've mistaken the command for antigen (`antigen bundle subnixr/minimal`). I'm sorry, it's been a while since I last used antigen.

I've updated README accordingly.
