### ISSUE TITLE
How to deactivate Vi-Mode

### ISSUE THREAD

**Issue by stndrf** [subnixr/minimal#18]
I see no use for me to use the Vi-Mode, but i have struggle to deactivate it.

Probably it would be an idea to make an option to deactivate it like disableing magic enter

**Comment by subnixr** [comment]
Please, take a moment to read the [README](https://github.com/subnixr/minimal/blob/master/README.md) before opening issues:

> Minimal is mostly a collection of *components* (shell functions) on top of a thin layer to ease customization.

> Three global arrays handle the definition and rendering position of the components:
>
> ```
> # Components on the left prompt
> MNML_PROMPT=(mnml_ssh mnml_pyenv mnml_status mnml_keymap)
> 
> # Components on the right prompt
> MNML_RPROMPT=('mnml_cwd 2 0' mnml_git)
> 
> # Components shown on info line
> MNML_INFOLN=(mnml_err mnml_jobs mnml_uhp mnml_files)
> ```

And [here](https://github.com/subnixr/minimal#available-components)'s a list of the available components, full with description and usage.

There's also an [example section](https://github.com/subnixr/minimal/blob/master/README.md#classic-bashs-prompt) which should help figuring out how to customize.

**Comment by stndrf** [comment]
I'm sorry, but i didn't spot the part where is explained how to deactivate the Normal/Insert-Mode (i read it before openening). I see parts how to turn off Magic Enter and Infoline, but i didn't found a part that tell me how to deactivate VI (just how to edit the chars ro remove ther char for it, which i like to keep - mnml_keymap).

Even desc of mnml_keymap just say, that it will remove the char and not that it will disable this.

Anyway thanks for your answer.

**Comment by subnixr** [comment]
vi bindings are managed by zsh itself, minimal just interacts with it.

But at this point, I'm not sure what you're asking...
