### ISSUE TITLE
Make Magic Enter OSX compatible

### ISSUE THREAD

**Issue by chaucerbao** [subnixr/minimal#2]
I believe the `ls` command in the [OSX version](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/ls.1.html) differs from the GNU version, so the Magic Enter is producing this error:

```
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
```

The issue is with the `--colors` argument. In OSX, the argument is `-G`.

https://github.com/subnixr/minimal/blob/master/minimal.zsh#L109

Just wanted to see if you were willing to do some sort of OS detection to use the appropriate arguments.

**Comment by subnixr** [comment]
> I believe the ls command in the OSX version differs from the GNU version

Yup, see [#1](https://github.com/subnixr/minimal/issues/1)

> Just wanted to see if you were willing to do some sort of OS detection to use the appropriate arguments.

Hopefully a `uname` should do the trick. I will try to look into this as soon as possible.

**Comment by subnixr** [comment]
[c714210](https://github.com/subnixr/minimal/commit/c71421010c9a2668628cc5c9bcf5c16828be1cc1) should fix it. Unfortunately, I don't have a OSX machine to test it right now

**Comment by chaucerbao** [comment]
Looking good!
