### ISSUE TITLE
Is there a way to change the color of `cwd`?

### ISSUE THREAD

**Issue by solomonxie** [subnixr/minimal#28]
Is there a way to change the text color of `cwd` rather than gray?
![image](https://user-images.githubusercontent.com/14041622/90355433-ea528880-e07e-11ea-9d7f-3c3e6069455b.png)

**Comment by subnixr** [comment]
No, the palette uses two user configurable colors (OK, ERR) and greyscale.

You can always copy `mnml_cwd` definition into your .zshrc and tweak it https://github.com/subnixr/minimal/blob/954ecdf602f22ec68f16e8c1991dcc47ebf729fb/minimal.zsh#L42-L71

Line 48 is grey color specification:
https://github.com/subnixr/minimal/blob/954ecdf602f22ec68f16e8c1991dcc47ebf729fb/minimal.zsh#L48

Be sure to update MNML_PROMPT accordingly.
