### ISSUE TITLE
Git unpushed commits color difference

### ISSUE THREAD

**Issue by samhh** [subnixr/minimal#3]
I've started using this theme since my previous ([S1cK94/minimal](https://github.com/S1cK94/minimal)) recommended doing so.

One key difference and weakness of this theme for me is that unlike S1cK94's theme, there is no difference in color in a git repository between unpushed commits and pushed commits/up to date with remote.

S1cK94's theme used white to represent unpushed commits and I found it very useful. Could you implement the same?

For reference the repo linked above has an image showing what this looks like.

Thanks and great theme!

**Comment by subnixr** [comment]
> I've started using this theme since my previous (S1cK94/minimal) recommended doing so.

Glad you're here :)

> One key difference and weakness of this theme for me is that unlike S1cK94's theme, there is no difference in color in a git repository between unpushed commits and pushed commits/up to date with remote.

Unpushed changes can be useful, but is it necessary in the prompt? I would instead put it in the magic enter, alongside git status output.

Eventually (with some refactoring - which I should do) one can set whatever command he/she wants to display as output.

**Comment by samhh** [comment]
It's helpful to know that sort of information before you perform certain actions such as pulling/pushing. For me it should be immediately visible because, like the branch and the edited/unedited status, it's contextual.

**Comment by subnixr** [comment]
Alrigth, after [this commit][1] I added the ability to override parts of the theme (see [README.md][2]). I still don't like to use more than one color in the prompt, but indeed it's useful to see the repo status, so I added it in the default `minimal_magic_output` function.

You can always define a custom `minimal_vcs` function before sourcing `minimal.zsh` that does what you want.

[1]: https://github.com/subnixr/minimal/commit/5f04c88c92bb1b81c0f2a9aa901f405a0c86cb27
[2]: https://github.com/subnixr/minimal/blob/master/README.md

**Comment by samhh** [comment]
That's worked great for me, thanks @subnixr.

If anyone stumbles upon this and wants more colours based upon git status, here's what I came up with:

```bash
minimal_vcs() {
  # git
  local branchName
  branchName="$(git rev-parse --abbrev-ref HEAD 2> /dev/null)"

  if [ -n "$branchName" ]; then
    local localRemoteState
    localRemoteState="$(git status --porcelain -b)"

    local color
    if echo "$localRemoteState" | grep -v '^##' &> /dev/null; then
      # dirty
      color="1" # red
    elif echo "$localRemoteState" | grep '^## .*diverged' &> /dev/null; then
      # diverged
      color="5" # magenta
    elif echo "$localRemoteState" | grep '^## .*behind' &> /dev/null; then
      # behind
      color="4" # blue
    elif echo "$localRemoteState" | grep '^## .*ahead' &> /dev/null; then
      # ahead
      color="7" # white
    else
      # clean
      color=$MINIMAL_OK_COLOR # green by default
    fi

    local formattedColor="%{\e[0;3${color}m%}"

    echo -n " $formattedColor$branchName%{\e[0m%}"
  fi
}
```

Via: https://github.com/SamHH/dotfiles/commit/7f84c6ee1d87fa1e2d902b2459b03c42af180d7a

Edit: I've turned this into a plugin/theme that you can source! :-) https://github.com/SamHH/minimal-colorful-git-status
