### ISSUE TITLE
How to configure if installed from the AUR?

### ISSUE THREAD

**Issue by ab1nn** [subnixr/minimal#31]
How to use this if installed from the AUR? Like is there something to source to .zshrc or anything like that?

**Comment by ab1nn** [comment]
Sorry my bad. I should have done a little more research. (But I still suggest the developer to add a manual installation tutorial in the readme also).

For those who are here for this:
`source /usr/share/zsh/plugins/theme-minimal/minimal.zsh`
Add this to `.zshrc`. Any plugins downloaded from AUR can be added like this without using a plugin manager.

**Comment by subnixr** [comment]
You're assuming that the developer has written the PKGBUILD and submitted it to the AUR: unfortunately I never did any of those. Can you please confirm you're referring to [this][1] PKGBUILD?

I'm glad tho, even if I wish I had been informed from whoever did it with an email or PM.

> Otherwise, you can always clone the repo and source `minimal.zsh`.

I agree this line goes a bit unnoticed in the docs. I'm open for suggestion on how to improve it

[1]: https://aur.archlinux.org/packages/zsh-theme-minimal/

**Comment by ab1nn** [comment]
Ooh. The upstream URL in that AUR package directs to here. So I thought it would be you itself. 
I am sorry I didn't notice that. I am much of newbie myself. So was expecting a heading like the others for a manual install tutorial. My bad. And thanks for this project.
