### ISSUE TITLE
Add config option to change length of right prompt directory length

### ISSUE THREAD

**Issue by samhh** [subnixr/minimal#4]
See here from README:

> The last two segments of pwd are shown. If a segment is longer than 10 chars, it will be ellipsed. If you are near the root (eg: /usr/bin) the first slash will be shown.

I'd love to be able to configure this to something bigger - my terminal is always using 100% of my hires laptop display so I'd personally set it to something like 30 chars.

Config option the best approach with a default of 10?

**Comment by subnixr** [comment]
Thanks for the tip, some basic math did the job.

I also added an option to display more (or less) than 2 segments of `pwd` in the right prompt

**Comment by samhh** [comment]
@subnixr Super minor thing, there's a type here:

> overrides maximu**n** length of pwd

Cheers!

**Comment by samhh** [comment]
Also:

> overrides color for **succefull**

**Comment by samhh** [comment]
By the way, this change is working perfectly for me. Many thanks! :-)

**Comment by subnixr** [comment]
typos fixed
